
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Salman
 */
public class admCustomer extends javax.swing.JFrame {
    String custId;
    String custPickName;
    String custPickPhone;
    String custPickAddress;
    String custPickPinCode;
    String custPickState;
    String custDelName;
    String custDelPhone;
    String custDelAddress;
    String custDelPinCode;
    String custDelState;
    public admCustomer() {
        initComponents();
        fetchDataFromDb();
    }
    public void fetchDataFromDb()
    {
        String connectionUrl = "jdbc:sqlserver://localhost:1433;databasename=courier;integratedSecurity=true";
        try (Connection con = DriverManager.getConnection(connectionUrl); ) 
        {               
            PreparedStatement pst=con.prepareStatement("Select * from cust_tbl"); 
            ResultSet rs = pst.executeQuery();           
            while(rs.next())
            {
              custId=String.valueOf(rs.getInt("custId"));
              custPickName=rs.getString("custPickName");
              custPickPhone=rs.getString("custPickPhone");
              custPickAddress=rs.getString("custPickAddress");
              custPickPinCode=rs.getString("custPickPinCode");
              custPickState=rs.getString("custPickState");
              custDelName=rs.getString("custDelName");
              custDelPhone=rs.getString("custDelPhone");
              custDelAddress=rs.getString("custDelAddress");
              custDelPinCode=rs.getString("custDelPinCode");
              custDelState=rs.getString("custDelState");
              String tbData[]={custId,custPickName,custPickPhone,custPickAddress,custPickPinCode,custPickState,custDelName,custDelPhone,custDelAddress,custDelPinCode,custDelState};
              DefaultTableModel tblModel=(DefaultTableModel)adm_Customer_Table.getModel();   
              tblModel.addRow(tbData);
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        adm_Customer_Table = new javax.swing.JTable();
        adm_cust_Id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        adm_emp_New = new javax.swing.JButton();
        adm_emp_Update = new javax.swing.JButton();
        adm_cust_Pick_Phone = new javax.swing.JTextField();
        adm_cust_Pick_Name = new javax.swing.JTextField();
        adm_cust_Pick_PinCode = new javax.swing.JTextField();
        adm_cust_Pick_Address = new javax.swing.JTextField();
        adm_cust_Pick_State = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        adm_emp_Remove = new javax.swing.JButton();
        adm_cust_Del_Phone = new javax.swing.JTextField();
        adm_cust_Del_Name = new javax.swing.JTextField();
        adm_cust_Del_Address = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        adm_cust_Del_PinCode = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        adm_cust_Del_State = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        adm_Customer_Table.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        adm_Customer_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "custId", "custPickName", "custPickPhone", "custPickAddress", "custPickPinCode", "custPickState", "custDelName", "custDelPhone", "custDelAddress", "custDelPinCode", "custDelState"
            }
        ));
        adm_Customer_Table.setPreferredSize(new java.awt.Dimension(1000, 655));
        adm_Customer_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adm_Customer_TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(adm_Customer_Table);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("ID");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Sende_ Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Sender_Phone");

        adm_emp_New.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adm_emp_New.setText("New");
        adm_emp_New.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        adm_emp_New.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adm_emp_NewActionPerformed(evt);
            }
        });

        adm_emp_Update.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adm_emp_Update.setText("Update");
        adm_emp_Update.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        adm_emp_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adm_emp_UpdateActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Sender_State");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Sender_Pincode");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Sender_Address");

        adm_emp_Remove.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adm_emp_Remove.setText("Remove");
        adm_emp_Remove.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        adm_emp_Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adm_emp_RemoveActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Reciever_Address");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Reciever_Phone");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Reciever_Name");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Reciever_PinCode");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Reciever_State");

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Customer Details");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/backbtn.png"))); // NOI18N
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(20, 20, 20))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(adm_cust_Pick_Name)
                                    .addComponent(adm_cust_Pick_Phone)
                                    .addComponent(adm_cust_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(adm_cust_Pick_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(adm_cust_Pick_PinCode, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(20, 20, 20)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(adm_cust_Del_Phone)
                                            .addComponent(adm_cust_Del_Name)
                                            .addComponent(adm_cust_Pick_State, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(adm_cust_Del_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(adm_cust_Del_State, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(adm_cust_Del_PinCode, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(adm_emp_New, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(adm_emp_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(adm_emp_Remove, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(74, 74, 74))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adm_cust_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(adm_cust_Pick_PinCode, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adm_cust_Del_Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adm_cust_Pick_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(adm_cust_Pick_State, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adm_cust_Del_PinCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adm_cust_Pick_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9)
                    .addComponent(adm_cust_Del_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adm_cust_Del_State, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(adm_cust_Pick_Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adm_cust_Del_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adm_emp_New, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adm_emp_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adm_emp_Remove, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adm_Customer_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adm_Customer_TableMouseClicked
        int i=adm_Customer_Table.getSelectedRow();
        TableModel model=adm_Customer_Table.getModel();
        adm_cust_Id.setText(model.getValueAt(i, 0).toString());
        adm_cust_Pick_Name.setText(model.getValueAt(i, 1).toString());

        adm_cust_Pick_Phone.setText(model.getValueAt(i, 2).toString());
        adm_cust_Pick_Address.setText(model.getValueAt(i, 3).toString());
        adm_cust_Pick_PinCode.setText(model.getValueAt(i, 4).toString());
        adm_cust_Pick_State.setText(model.getValueAt(i, 5).toString());
        adm_cust_Del_Name.setText(model.getValueAt(i, 6).toString());

        adm_cust_Del_Phone.setText(model.getValueAt(i, 7).toString());
        adm_cust_Del_Address.setText(model.getValueAt(i, 8).toString());
        adm_cust_Del_PinCode.setText(model.getValueAt(i, 9).toString());
        adm_cust_Del_State.setText(model.getValueAt(i, 10).toString());
        
        //--------Assigning values to class Variables so that it can be used by any methods--------//
        
        custId=model.getValueAt(i, 0).toString();
        custPickName=model.getValueAt(i, 1).toString();
        custPickPhone=model.getValueAt(i, 2).toString();
        custPickAddress=model.getValueAt(i, 3).toString();
        custPickPinCode=model.getValueAt(i, 4).toString();
        custPickState=model.getValueAt(i, 5).toString();
        custDelName=model.getValueAt(i, 6).toString();
        custDelPhone=model.getValueAt(i, 7).toString();
        custDelAddress=model.getValueAt(i, 8).toString();
        custDelPinCode=model.getValueAt(i, 9).toString();
        custDelState=model.getValueAt(i, 10).toString();

    }//GEN-LAST:event_adm_Customer_TableMouseClicked

    private void adm_emp_NewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adm_emp_NewActionPerformed
        String connectionUrl = "jdbc:sqlserver://localhost:1433;databasename=courier;integratedSecurity=true";
        try(Connection con = DriverManager.getConnection(connectionUrl);)
        {
            if(!(adm_cust_Id.getText().equals("") ||adm_cust_Pick_Name.getText().equals("") ||adm_cust_Pick_Phone.getText().equals("") ||adm_cust_Pick_Address.getText().equals("") || adm_cust_Pick_PinCode.getText().equals("")||adm_cust_Pick_State.getText().equals("")||adm_cust_Del_Name.getText().equals("")||adm_cust_Del_Phone.getText().equals("")||adm_cust_Del_Address.getText().equals("")||adm_cust_Del_PinCode.getText().equals("")||adm_cust_Del_State.getText().equals("")))
            {
                custId=adm_cust_Id.getText();
                custPickName=adm_cust_Pick_Name.getText();
                custPickPhone=adm_cust_Pick_Phone.getText();
                custPickAddress=adm_cust_Pick_Address.getText();
                custPickPinCode=adm_cust_Pick_PinCode.getText();
                custPickState=adm_cust_Pick_State.getText();
                custDelName=adm_cust_Del_Name.getText();
                custDelPhone=adm_cust_Del_Phone.getText();
                custDelAddress=adm_cust_Del_Address.getText();
                custDelPinCode=adm_cust_Del_PinCode.getText();
                custDelState=adm_cust_Del_State.getText();
                
                System.out.println(custId+" "+custPickName+" "+custPickPhone+" "+custPickAddress+" "+custPickPinCode+" "+custPickState+" "+custDelName
                +" "+custDelPhone+" "+custDelAddress+" "+custDelPinCode+" "+custDelState);
                PreparedStatement ps = con.prepareStatement("insert into cust_tbl(custPickName,custPickPhone,"
                        + "custPickAddress,custPickPinCode,custPickState,custDelName,custDelPhone,custDelAddress,custDelPinCode,custDelState) values(?,?,?,?,?,?,?,?,?,?)");
                ps.setString(1,custPickName);
                ps.setString(2,custPickPhone);
                ps.setString(3,custPickAddress);
                ps.setString(4,custPickPinCode);
                ps.setString(5,custPickState);
                ps.setString(6,custDelName);
                ps.setString(7,custDelPhone);
                ps.setString(8,custDelAddress);
                ps.setString(9,custDelPinCode);
                ps.setString(10,custDelState);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this,"Customers Inserted Successfully");
                new admCustomer().setVisible(true);
                this.dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(this,"All Fields are mandatory");
            }
        }
        catch(Exception e)
        {
            System.out.println(e);

        }
    }//GEN-LAST:event_adm_emp_NewActionPerformed

    private void adm_emp_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adm_emp_UpdateActionPerformed
        String connectionUrl = "jdbc:sqlserver://localhost:1433;databasename=courier;integratedSecurity=true";
        try(Connection con = DriverManager.getConnection(connectionUrl);)
        {
            if(!(adm_cust_Id.getText().equals("")
                    ||adm_cust_Pick_Name.getText().equals("")
                    ||adm_cust_Pick_Phone.getText().equals("")
                    ||adm_cust_Pick_Address.getText().equals("")
                    || adm_cust_Pick_PinCode.getText().equals("")
                    ||adm_cust_Pick_State.getText().equals("")
                    ||adm_cust_Del_Name.getText().equals("")
                    ||adm_cust_Del_Phone.getText().equals("")
                    ||adm_cust_Del_Address.getText().equals("")
                    ||adm_cust_Del_PinCode.getText().equals("")
                    ||adm_cust_Del_State.getText().equals("")))  
                {
                custId=adm_cust_Id.getText();
                custPickName=adm_cust_Pick_Name.getText();
                custPickPhone=adm_cust_Pick_Phone.getText();
                custPickAddress=adm_cust_Pick_Address.getText();
                custPickPinCode=adm_cust_Pick_PinCode.getText();
                custPickState=adm_cust_Pick_State.getText();
                custDelName=adm_cust_Del_Name.getText();
                custDelPhone=adm_cust_Del_Phone.getText();
                custDelAddress=adm_cust_Del_Address.getText();
                custDelPinCode=adm_cust_Del_PinCode.getText();
                custDelState=adm_cust_Del_State.getText();
                PreparedStatement ps = con.prepareStatement("UPDATE cust_tbl SET custPickName=?,custPickPhone=?,custPickAddress=?,custPickPinCode=?,custPickState=?,custDelName=?,custDelPhone=?,custDelAddress=?,custDelPinCode=?,custDelState=? WHERE custId=?");
                ps.setString(1,custPickName);
                ps.setString(2,custPickPhone);
                ps.setString(3,custPickAddress);
                ps.setString(4,custPickPinCode);
                ps.setString(5,custPickState);
                ps.setString(6,custDelName);
                ps.setString(7,custDelPhone);
                ps.setString(8,custDelAddress);
                ps.setString(9,custDelPinCode);
                ps.setString(10,custDelState);
                ps.setString(11,custId);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this,"Employess Updated Successfully");
                new admCustomer().setVisible(true);
                this.dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(this,"All Fields are mandatory");
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_adm_emp_UpdateActionPerformed

    private void adm_emp_RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adm_emp_RemoveActionPerformed
        String connectionUrl = "jdbc:sqlserver://localhost:1433;databasename=courier;integratedSecurity=true";
        try(Connection con = DriverManager.getConnection(connectionUrl);)
        {
            if(!(adm_cust_Id.getText().equals("") ))
            {
                custId=adm_cust_Id.getText();
                PreparedStatement ps = con.prepareStatement("DELETE from cust_tbl WHERE custId = ?");
                ps.setString(1,custId);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this,"Customer Deleted Successfully");
                new admCustomer().setVisible(true);
                this.dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(this,"All Fields are mandatory");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,"Error"+e);
        }
    }//GEN-LAST:event_adm_emp_RemoveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new admin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable adm_Customer_Table;
    private javax.swing.JTextField adm_cust_Del_Address;
    private javax.swing.JTextField adm_cust_Del_Name;
    private javax.swing.JTextField adm_cust_Del_Phone;
    private javax.swing.JTextField adm_cust_Del_PinCode;
    private javax.swing.JTextField adm_cust_Del_State;
    private javax.swing.JTextField adm_cust_Id;
    private javax.swing.JTextField adm_cust_Pick_Address;
    private javax.swing.JTextField adm_cust_Pick_Name;
    private javax.swing.JTextField adm_cust_Pick_Phone;
    private javax.swing.JTextField adm_cust_Pick_PinCode;
    private javax.swing.JTextField adm_cust_Pick_State;
    private javax.swing.JButton adm_emp_New;
    private javax.swing.JButton adm_emp_Remove;
    private javax.swing.JButton adm_emp_Update;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
